In [49]:
import duckdb
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression

# Load the Postgres extension
duckdb.sql("INSTALL postgres_scanner;")
duckdb.sql("LOAD postgres_scanner;")

# credentials
pg_conn_str = "dbname='mimic-iii' user='sangeethgeorge' password='12345' host='localhost' port='5432'"

#SQL query to connect to DB
labs48_query = """
SELECT *
FROM postgres_scan('dbname=mimic-iii user=sangeethgeorge password=12345 host=localhost port=5432', 
                   'public', 'all_labs_48h')
"""
vitals48_query = """
SELECT *
FROM postgres_scan('dbname=mimic-iii user=sangeethgeorge password=12345 host=localhost port=5432', 
                   'public', 'all_vitals_48h')
"""

onc_cohort = """
SELECT *
FROM postgres_scan('dbname=mimic-iii user=sangeethgeorge password=12345 host=localhost port=5432', 
                   'public', 'oncology_icu_base')
"""

labs48_df= duckdb.sql(labs48_query).df()
vitals48_df = duckdb.sql(vitals48_query).df()
onc_cohort_df = duckdb.sql(onc_cohort).df()

In [28]:
labs48_df

,subject_id,hadm_id,icustay_id,icd9_code,short_title,itemid,labs_label,fluid,labs_category,charttime,labs_valuenum,labs_valueom,flag
0,18778,195341,260056,1912,Mal neo temporal lobe,51347,Eosinophils,Cerebrospinal Fluid (CSF),Hematology,2106-02-19 02:00:00,2.0,%,None
1,32458,182671,207405,2395,Other gu neoplasm NOS,51347,Eosinophils,Cerebrospinal Fluid (CSF),Hematology,2170-02-16 18:00:00,3.0,%,None
2,32458,182671,207405,1985,Secondary malig neo bone,51347,Eosinophils,Cerebrospinal Fluid (CSF),Hematology,2170-02-16 18:00:00,3.0,%,None
3,32458,182671,207405,1977,Second malig neo liver,51347,Eosinophils,Cerebrospinal Fluid (CSF),Hematology,2170-02-16 18:00:00,3.0,%,None
4,32458,182671,207405,1961,Mal neo lymph-intrathor,51347,Eosinophils,Cerebrospinal Fluid (CSF),Hematology,2170-02-16 18:00:00,3.0,%,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...
314529,98525,168505,294539,1534,Malignant neoplasm cecum,51516,WBC,Urine,Hematology,2146-06-28 11:36:00,10.0,#/hpf,abnormal
314530,97217,124771,273075,1551,Mal neo intrahepat ducts,51516,WBC,Urine,Hematology,2123-04-16 20:00:00,70.0,#/hpf,abnormal
314531,96676,119628,257147,1912,Mal neo temporal lobe,51516,WBC,Urine,Hematology,2159-02-25 17:40:00,0.0,#/hpf,None
314532,99865,189346,284772,1550,"Mal neo liver, primary",51516,WBC,Urine,Hematology,2184-12-24 11:24:00,12.0,#/hpf,abnormal
314533,98805,122631,203155,1890,Malig neopl kidney,51516,WBC,Urine,Hematology,2200-09-12 22:11:00,1.0,#/hpf,None

In [29]:
vitals48_df

,subject_id,hadm_id,icustay_id,icd9_code,short_title,itemid,vitals_label,vitals_category,dbsource,charttime,vitals_valuenum,vitals_valueuom
0,26088,194863,202891,185,Malign neopl prostate,25.0,AV Interval,None,carevue,2154-04-30,200.000000,msec
1,26088,194863,202891,185,Malign neopl prostate,25.0,AV Interval,None,carevue,2154-04-30,200.000000,msec
2,26088,194863,202891,185,Malign neopl prostate,25.0,AV Interval,None,carevue,2154-04-30,200.000000,msec
3,23412,132933,212872,1625,Mal neo lower lobe lung,26.0,AaDO2,None,carevue,2120-11-18,501.000000,mmHg
4,9779,110839,221891,1888,Malig neo bladder NEC,26.0,AaDO2,None,carevue,2134-12-24,45.549999,mmHg
...,...,...,...,...,...,...,...,...,...,...,...,...
1684789,50618,153677,222744,1983,Sec mal neo brain/spine,228412.0,Strength R Arm,Neurological,metavision,2151-07-28,5.000000,None
1684790,50618,153677,222744,1623,Mal neo upper lobe lung,228412.0,Strength R Arm,Neurological,metavision,2151-07-28,5.000000,None
1684791,94009,104613,223479,2252,Ben neo cerebr meninges,228412.0,Strength R Arm,Neurological,metavision,2129-08-11,5.000000,None
1684792,45040,120255,222194,185,Malign neopl prostate,228412.0,Strength R Arm,Neurological,metavision,2183-09-07,4.000000,None
1684793,71375,172733,221553,1983,Sec mal neo brain/spine,228412.0,Strength R Arm,Neurological,metavision,2149-06-15,4.000000,None

In [30]:
onc_cohort_df

,subject_id,hadm_id,icustay_id,icd9_code,short_title,intime,outtime,gender,dob,dod,admittime,ethnicity,marital_status,insurance,admission_type,age,mortality_30d
0,84,166401,239661,1919,Malig neo brain NOS,2196-04-16 23:43:00,2196-04-17 13:42:00,F,2151-10-21,2196-04-17,2196-04-14 04:02:00,WHITE,MARRIED,Private,EMERGENCY,44.0,1
1,113,109976,224661,1915,Mal neo cereb ventricle,2140-12-12 22:48:08,2140-12-13 17:42:46,M,2105-02-09,NaT,2140-12-12 22:46:00,WHITE,MARRIED,Private,EMERGENCY,35.0,0
2,11,194540,229441,1913,Mal neo parietal lobe,2178-04-16 06:19:32,2178-04-17 20:21:05,F,2128-02-22,2178-11-14,2178-04-16 06:18:00,WHITE,MARRIED,Private,EMERGENCY,50.0,0
3,505,116719,257903,1970,Secondary malig neo lung,2154-03-30 14:59:43,2154-03-31 16:35:08,M,2097-11-23,2154-08-29,2154-03-30 14:59:00,WHITE,MARRIED,Private,EMERGENCY,56.0,0
4,505,116719,257903,1985,Secondary malig neo bone,2154-03-30 14:59:43,2154-03-31 16:35:08,M,2097-11-23,2154-08-29,2154-03-30 14:59:00,WHITE,MARRIED,Private,EMERGENCY,56.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4265,98701,124568,292251,179,Malig neopl uterus NOS,2136-03-01 21:31:34,2136-03-02 18:35:05,F,2082-03-31,2136-03-11,2136-03-01 21:30:00,WHITE,MARRIED,Private,EMERGENCY,53.0,1
4266,98701,124568,292251,1976,Sec mal neo peritoneum,2136-03-01 21:31:34,2136-03-02 18:35:05,F,2082-03-31,2136-03-11,2136-03-01 21:30:00,WHITE,MARRIED,Private,EMERGENCY,53.0,1
4267,98701,124568,292251,1977,Second malig neo liver,2136-03-01 21:31:34,2136-03-02 18:35:05,F,2082-03-31,2136-03-11,2136-03-01 21:30:00,WHITE,MARRIED,Private,EMERGENCY,53.0,1
4268,98701,124568,292251,1978,Sec mal neo GI NEC,2136-03-01 21:31:34,2136-03-02 18:35:05,F,2082-03-31,2136-03-11,2136-03-01 21:30:00,WHITE,MARRIED,Private,EMERGENCY,53.0,1
4269,98805,122631,203155,1890,Malig neopl kidney,2200-09-12 19:25:51,2200-09-14 18:17:01,M,2158-03-02,NaT,2200-09-12 07:15:00,WHITE,MARRIED,Private,ELECTIVE,42.0,0

In [37]:
# Clean & Prepare
labs48_df['charttime'] = pd.to_datetime(labs48_df['charttime'])
labs48_df.dropna(subset=['labs_valuenum'], inplace=True)

# Clean & Prepare
vitals48_df['charttime'] = pd.to_datetime(vitals48_df['charttime'])
vitals48_df.dropna(subset=['vitals_valuenum'], inplace=True)

In [47]:
# --- High Coverage Vitals ---

# 1. Calculate the coverage for each vital label (percentage of unique ICU stays it appears in)
total_unique_stays = vitals48_df['icustay_id'].nunique()
vitals48_coverage = vitals48_df.groupby('vitals_label')['icustay_id'].nunique() / total_unique_stays

# 2. Define your high coverage threshold (e.g., 0.8 for 80%)
coverage_threshold = 0.7

# 3. Filter to get only the labels that meet the high coverage threshold
high_coverage_labels = vitals48_coverage[vitals48_coverage >= coverage_threshold].index.tolist()

print("Labels with High Coverage (>= {}%):".format(coverage_threshold * 100))
print(high_coverage_labels)

# 4. Filter the original DataFrame to include only these high-coverage labels
filtered_vitals_df_high_coverage = vitals48_df[vitals48_df['vitals_label'].isin(high_coverage_labels)]

# 5. Calculate unique ICU stays for each of the high-coverage labels
unique_stays_per_high_coverage_label = filtered_vitals_df_high_coverage.groupby('vitals_label')['icustay_id'].nunique()

# 6. Calculate the percentage of unique ICU stays for each high-coverage label
#    (This is essentially `vitals48_coverage` for the selected labels, but we recalculate
#     it here to fit the structure of the original code's output)
percentage_unique_stays_high_coverage = (unique_stays_per_high_coverage_label / total_unique_stays) * 100

# 7. Combine the counts and percentages for better readability
vitals48_high_coverage_pct_df = pd.DataFrame({
    'Unique ICU Stays Count': unique_stays_per_high_coverage_label,
    'Percentage of Total Unique ICU Stays': percentage_unique_stays_high_coverage
}).sort_values(by='Percentage of Total Unique ICU Stays', ascending=False)

vitals48_high_coverage_pct_df

Labels with High Coverage (>= 70.0%):
['BUN', 'Creatinine', 'Heart Rate', 'Hemoglobin', 'Magnesium', 'Phosphorous', 'Respiratory Rate', 'WBC']

                  Unique ICU Stays Count  Percentage of Total Unique ICU Stays
vitals_label
Heart Rate                          2373                             99.205686
Respiratory Rate                    2363                             98.787625
Hemoglobin                          2242                             93.729097
Creatinine                          2003                             83.737458
BUN                                 2001                             83.653846
WBC                                 1996                             83.444816
Magnesium                           1922                             80.351171
Phosphorous                         1857                             77.633779

In [46]:
# --- High Coverage Labs ---

# 1. Calculate the coverage for each vital label (percentage of unique ICU stays it appears in)
total_unique_stays = labs48_df['icustay_id'].nunique()
labs48_coverage = labs48_df.groupby('labs_label')['icustay_id'].nunique() / total_unique_stays

# 2. Define your high coverage threshold (e.g., 0.8 for 80%)
coverage_threshold = 0.7

# 3. Filter to get only the labels that meet the high coverage threshold
high_coverage_labels = labs48_coverage[labs48_coverage >= coverage_threshold].index.tolist()

print("Labels with High Coverage (>= {}%):".format(coverage_threshold * 100))
print(high_coverage_labels)

# 4. Filter the original DataFrame to include only these high-coverage labels
filtered_labs_df_high_coverage = labs48_df[labs48_df['labs_label'].isin(high_coverage_labels)]

# 5. Calculate unique ICU stays for each of the high-coverage labels
unique_stays_per_high_coverage_label = filtered_labs_df_high_coverage.groupby('labs_label')['icustay_id'].nunique()

# 6. Calculate the percentage of unique ICU stays for each high-coverage label
#    (This is essentially `labs48_coverage` for the selected labels, but we recalculate
#     it here to fit the structure of the original code's output)
percentage_unique_stays_high_coverage = (unique_stays_per_high_coverage_label / total_unique_stays) * 100

# 7. Combine the counts and percentages for better readability
labs48_high_coverage_pct_df = pd.DataFrame({
    'Unique ICU Stays Count': unique_stays_per_high_coverage_label,
    'Percentage of Total Unique ICU Stays': percentage_unique_stays_high_coverage
}).sort_values(by='Percentage of Total Unique ICU Stays', ascending=False)

labs48_high_coverage_pct_df

Labels with High Coverage (>= 70.0%):
['Anion Gap', 'Bicarbonate', 'Calcium, Total', 'Chloride', 'Creatinine', 'Glucose', 'Hematocrit', 'Hemoglobin', 'INR(PT)', 'MCH', 'MCHC', 'MCV', 'Magnesium', 'PT', 'PTT', 'Phosphate', 'Platelet Count', 'Potassium', 'RDW', 'Red Blood Cells', 'Sodium', 'Urea Nitrogen', 'White Blood Cells']

,Unique ICU Stays Count,Percentage of Total Unique ICU Stays
labs_label,,
Glucose,2427,99.182673
Potassium,2426,99.141806
Sodium,2422,98.978341
Urea Nitrogen,2421,98.937474
Chloride,2421,98.937474
Creatinine,2421,98.937474
Bicarbonate,2420,98.896608
Anion Gap,2419,98.855742
Hematocrit,2418,98.814875
Hemoglobin,2412,98.569677
Platelet Count,2408,98.406212
White Blood Cells,2407,98.365345
MCHC,2404,98.242746
MCH,2404,98.242746
Red Blood Cells,2404,98.242746
MCV,2404,98.242746
RDW,2403,98.201880
Magnesium,2363,96.567225
Phosphate,2270,92.766653
"Calcium, Total",2263,92.480588
PT,1893,77.360033
INR(PT),1893,77.360033
PTT,1870,76.420106

In [109]:
# --- High Coverage Vitals ---

# 1. Calculate the coverage for each vital label (percentage of unique ICU stays it appears in)
total_unique_stays = vitals48_df['icustay_id'].nunique()
vitals48_coverage = vitals48_df.groupby('vitals_label')['icustay_id'].nunique() / total_unique_stays

# 2. Define your high coverage threshold (e.g., 0.8 for 80%)
coverage_threshold = 0.7

# 3. Filter to get only the labels that meet the high coverage threshold
high_coverage_labels = vitals48_coverage[vitals48_coverage >= coverage_threshold].index.tolist()

print("Labels with High Coverage (>= {}%):".format(coverage_threshold * 100))
print(high_coverage_labels)

# 4. Filter the original DataFrame to include only these high-coverage labels
filtered_vitals_df_high_coverage = vitals48_df[vitals48_df['vitals_label'].isin(high_coverage_labels)]

# 5. Calculate unique ICU stays for each of the high-coverage labels
unique_stays_per_high_coverage_label = filtered_vitals_df_high_coverage.groupby('vitals_label')['icustay_id'].nunique()

# 6. Calculate the percentage of unique ICU stays for each high-coverage label
percentage_unique_stays_high_coverage = (unique_stays_per_high_coverage_label / total_unique_stays) * 100

# 7. Combine the counts and percentages for better readability
vitals48_high_coverage_pct_df = pd.DataFrame({
    'Unique ICU Stays Count': unique_stays_per_high_coverage_label,
    'Percentage of Total Unique ICU Stays': percentage_unique_stays_high_coverage
}).sort_values(by='Percentage of Total Unique ICU Stays', ascending=False)

vitals48_high_coverage_pct_df

# Start from your filtered long-form vitals
df = filtered_vitals_df_high_coverage.copy()

# Convert charttime to datetime if not already (redundant if already done, but safe)
df['charttime'] = pd.to_datetime(df['charttime'])

# Feature engineering function per vital per ICU stay
def compute_time_series_features(group):
    # Ensure times and values are numpy arrays for reshape
    times = (group['charttime'] - group['charttime'].min()).dt.total_seconds().values / 3600.0  # in hours
    values = group['vitals_valuenum'].values

    # Defensive check
    if len(values) < 1:
        return pd.Series({'mean': np.nan, 'min': np.nan, 'max': np.nan, 'slope': np.nan})

    # Compute features
    features = {
        'mean': np.mean(values),
        'min': np.min(values),
        'max': np.max(values),
    }

    # Linear regression slope over time
    if len(values) > 1:
        # Use .reshape(-1, 1) on the NumPy array obtained from .values
        model = LinearRegression().fit(times.reshape(-1, 1), values)
        features['slope'] = model.coef_[0]
    else:
        features['slope'] = np.nan

    return pd.Series(features)

# Group by ICU stay and label â†’ apply function
grouped = df.groupby(['icustay_id', 'vitals_label'])
vitals_features_df = grouped.apply(compute_time_series_features, include_groups=False).reset_index()
# Pivot to wide format
vitals_features_wide = vitals_features_df.pivot(index='icustay_id', columns='vitals_label')
vitals_features_wide.columns = [f"{stat.lower()}_{label.lower().replace(' ', '_')}" for stat, label in vitals_features_wide.columns]
vitals_features_wide.reset_index(inplace=True)


vitals_features_wide

Labels with High Coverage (>= 70.0%):
['BUN', 'Creatinine', 'Heart Rate', 'Hemoglobin', 'Magnesium', 'Phosphorous', 'Respiratory Rate', 'WBC']

,icustay_id,mean_bun,mean_creatinine,mean_heart_rate,mean_hemoglobin,mean_magnesium,mean_phosphorous,mean_respiratory_rate,mean_wbc,min_bun,...,max_respiratory_rate,max_wbc,slope_bun,slope_creatinine,slope_heart_rate,slope_hemoglobin,slope_magnesium,slope_phosphorous,slope_respiratory_rate,slope_wbc
0,200035,17.000000,0.800000,106.777778,11.20,2.00,3.500000,21.555556,30.30,17.0,...,30.0,30.3,NaN,NaN,0.000000,NaN,NaN,NaN,0.000000,NaN
1,200044,31.000000,0.700000,67.562500,11.10,2.20,2.300000,14.066667,10.20,31.0,...,20.0,10.2,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
2,200163,15.500000,0.750000,68.185185,13.10,2.10,4.400000,16.148148,8.75,12.0,...,20.0,9.0,0.291667,0.004167,0.131944,-0.025000,0.000000,-0.041667,0.008681,-0.020833
3,200289,10.000000,0.700000,87.187500,13.80,1.60,3.800000,14.062500,25.70,10.0,...,19.0,25.7,NaN,NaN,0.000000,NaN,NaN,NaN,0.000000,NaN
4,200402,18.500000,0.800000,101.147059,9.55,2.05,4.000000,24.294118,6.65,17.0,...,31.0,7.0,0.125000,-0.000000,0.038542,-0.062500,-0.029167,-0.008333,-0.082292,-0.029167
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2368,299933,11.500000,0.700000,80.263158,14.30,2.15,2.600000,21.684211,12.50,11.0,...,29.0,13.7,0.041667,-0.008333,0.326637,-0.058333,0.012500,-0.100000,0.091518,-0.100000
2369,299947,20.500000,0.650000,68.972222,8.65,1.85,3.350000,13.666667,21.95,20.0,...,25.0,22.3,0.041667,0.004167,-0.465278,-0.062500,0.004167,-0.070833,-0.291667,0.029167
2370,299971,NaN,NaN,66.200000,8.50,NaN,NaN,16.600000,NaN,NaN,...,24.0,NaN,NaN,NaN,0.000000,NaN,NaN,NaN,0.000000,NaN
2371,299979,15.000000,0.800000,61.388889,10.30,2.10,2.900000,14.833333,16.00,15.0,...,23.0,16.0,NaN,NaN,0.000000,NaN,NaN,NaN,0.000000,NaN
2372,299998,20.333333,1.066667,83.230769,9.50,1.80,3.333333,14.102564,9.70,20.0,...,21.0,11.0,-0.020833,-0.004167,0.562160,-0.016667,0.000000,-0.027083,-0.007246,0.072222

In [110]:
# --- High Coverage labs ---

# 1. Calculate the coverage for each vital label (percentage of unique ICU stays it appears in)
total_unique_stays = labs48_df['icustay_id'].nunique()
labs48_coverage = labs48_df.groupby('labs_label')['icustay_id'].nunique() / total_unique_stays

# 2. Define your high coverage threshold (e.g., 0.8 for 80%)
coverage_threshold = 0.7

# 3. Filter to get only the labels that meet the high coverage threshold
high_coverage_labels = labs48_coverage[labs48_coverage >= coverage_threshold].index.tolist()

print("Labels with High Coverage (>= {}%):".format(coverage_threshold * 100))
print(high_coverage_labels)

# 4. Filter the original DataFrame to include only these high-coverage labels
filtered_labs_df_high_coverage = labs48_df[labs48_df['labs_label'].isin(high_coverage_labels)]

# 5. Calculate unique ICU stays for each of the high-coverage labels
unique_stays_per_high_coverage_label = filtered_labs_df_high_coverage.groupby('labs_label')['icustay_id'].nunique()

# 6. Calculate the percentage of unique ICU stays for each high-coverage label
percentage_unique_stays_high_coverage = (unique_stays_per_high_coverage_label / total_unique_stays) * 100

# 7. Combine the counts and percentages for better readability
labs48_high_coverage_pct_df = pd.DataFrame({
    'Unique ICU Stays Count': unique_stays_per_high_coverage_label,
    'Percentage of Total Unique ICU Stays': percentage_unique_stays_high_coverage
}).sort_values(by='Percentage of Total Unique ICU Stays', ascending=False)

labs48_high_coverage_pct_df

# Start from your filtered long-form labs
df = filtered_labs_df_high_coverage.copy()

# Convert charttime to datetime if not already (redundant if already done, but safe)
df['charttime'] = pd.to_datetime(df['charttime'])

# Feature engineering function per vital per ICU stay
def compute_time_series_features(group):
    # Ensure times and values are numpy arrays for reshape
    times = (group['charttime'] - group['charttime'].min()).dt.total_seconds().values / 3600.0  # in hours
    values = group['labs_valuenum'].values

    # Defensive check
    if len(values) < 1:
        return pd.Series({'mean': np.nan, 'min': np.nan, 'max': np.nan, 'slope': np.nan})

    # Compute features
    features = {
        'mean': np.mean(values),
        'min': np.min(values),
        'max': np.max(values),
    }

    # Linear regression slope over time
    if len(values) > 1:
        # Use .reshape(-1, 1) on the NumPy array obtained from .values
        model = LinearRegression().fit(times.reshape(-1, 1), values)
        features['slope'] = model.coef_[0]
    else:
        features['slope'] = np.nan

    return pd.Series(features)

# Group by ICU stay and label â†’ apply function
grouped = df.groupby(['icustay_id', 'labs_label'])
labs_features_df = grouped.apply(compute_time_series_features, include_groups=False).reset_index()
# Pivot to wide format
labs_features_wide = labs_features_df.pivot(index='icustay_id', columns='labs_label')
labs_features_wide.columns = [f"{stat.lower()}_{label.lower().replace(' ', '_')}" for stat, label in labs_features_wide.columns]
labs_features_wide.reset_index(inplace=True)

labs_features_wide

Labels with High Coverage (>= 70.0%):
['Anion Gap', 'Bicarbonate', 'Calcium, Total', 'Chloride', 'Creatinine', 'Glucose', 'Hematocrit', 'Hemoglobin', 'INR(PT)', 'MCH', 'MCHC', 'MCV', 'Magnesium', 'PT', 'PTT', 'Phosphate', 'Platelet Count', 'Potassium', 'RDW', 'Red Blood Cells', 'Sodium', 'Urea Nitrogen', 'White Blood Cells']

,icustay_id,mean_anion_gap,mean_bicarbonate,"mean_calcium,_total",mean_chloride,mean_creatinine,mean_glucose,mean_hematocrit,mean_hemoglobin,mean_inr(pt),...,slope_pt,slope_ptt,slope_phosphate,slope_platelet_count,slope_potassium,slope_rdw,slope_red_blood_cells,slope_sodium,slope_urea_nitrogen,slope_white_blood_cells
0,200035,12.000000,26.000000,8.400000,99.000000,0.750000,91.000000,33.800000,11.000000,1.700,...,NaN,NaN,-0.036364,-0.909091,-0.036364,0.013636,-0.012273,0.136364,-0.227273,-0.095455
1,200044,11.500000,24.000000,8.600000,102.000000,0.700000,101.500000,33.450000,11.750000,NaN,...,NaN,NaN,NaN,0.672823,0.007916,-0.003958,0.016623,0.039578,-0.316623,-0.003958
2,200163,12.666667,29.666667,9.533333,100.666667,0.733333,133.666667,39.200000,13.100000,1.125,...,-0.002067,0.612213,0.012500,-0.875912,0.008765,-0.008759,-0.000876,0.012500,0.337914,-0.021898
3,200289,13.000000,28.000000,8.900000,100.500000,0.700000,204.000000,38.400000,13.000000,1.200,...,NaN,NaN,-0.019557,-1.095176,0.019557,0.000000,-0.018774,0.039113,-0.117340,-0.418514
4,200402,11.666667,25.666667,9.333333,104.333333,0.766667,95.000000,26.300000,9.033333,NaN,...,NaN,NaN,-0.026603,-0.789039,-0.004303,-0.024015,-0.023230,-0.164558,0.020058,-0.046025
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2435,299933,12.666667,27.000000,8.233333,105.000000,0.700000,127.333333,40.800000,14.766667,NaN,...,NaN,NaN,-0.059832,-1.445581,0.010044,-0.025002,-0.023567,0.083522,0.033300,-0.094987
2436,299947,10.500000,29.500000,8.475000,97.250000,0.675000,164.500000,25.060000,8.940000,0.950,...,-0.033452,-0.057780,-0.072739,-0.468052,-0.017729,-0.005215,-0.019154,-0.042342,0.011372,0.120547
2437,299971,14.000000,24.000000,NaN,105.000000,0.800000,152.000000,24.900000,8.500000,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2438,299979,8.500000,25.000000,7.950000,107.000000,0.800000,137.500000,28.733333,9.600000,NaN,...,NaN,NaN,-0.048246,-3.427421,0.000000,0.017384,0.008798,0.043860,-0.087719,-0.281778
2439,299998,11.600000,24.000000,8.700000,108.800000,1.000000,169.600000,29.166667,9.550000,1.100,...,-0.016484,0.053571,-0.040034,-0.682022,-0.012254,0.002472,-0.012102,0.109076,-0.123193,0.022704

In [111]:
# Merge vitals
onco_feature_df = onc_cohort_df.merge(vitals_features_wide, on='icustay_id', how='left')

# Merge labs
onco_feature_df = onco_feature_df.merge(labs_features_wide, on='icustay_id', how='left')

onco_feature_df

,subject_id,hadm_id,icustay_id,icd9_code,short_title,intime,outtime,gender,dob,dod,...,slope_pt,slope_ptt,slope_phosphate,slope_platelet_count,slope_potassium,slope_rdw,slope_red_blood_cells,slope_sodium,slope_urea_nitrogen,slope_white_blood_cells
0,84,166401,239661,1919,Malig neo brain NOS,2196-04-16 23:43:00,2196-04-17 13:42:00,F,2151-10-21,2196-04-17,...,NaN,NaN,NaN,NaN,0.302158,NaN,NaN,2.374101,0.215827,NaN
1,113,109976,224661,1915,Mal neo cereb ventricle,2140-12-12 22:48:08,2140-12-13 17:42:46,M,2105-02-09,NaT,...,0.006849,0.140411,-0.010214,-0.776996,-0.010740,0.000000,-0.012172,-0.043983,0.024420,-0.075244
2,11,194540,229441,1913,Mal neo parietal lobe,2178-04-16 06:19:32,2178-04-17 20:21:05,F,2128-02-22,2178-11-14,...,NaN,NaN,NaN,-0.773861,-0.005159,0.005159,-0.007739,0.051591,0.257954,0.180567
3,505,116719,257903,1970,Secondary malig neo lung,2154-03-30 14:59:43,2154-03-31 16:35:08,M,2097-11-23,2154-08-29,...,0.000000,0.000000,-0.028645,0.473928,-0.003190,-0.024338,0.008389,0.040585,-0.068471,-0.018512
4,505,116719,257903,1985,Secondary malig neo bone,2154-03-30 14:59:43,2154-03-31 16:35:08,M,2097-11-23,2154-08-29,...,0.000000,0.000000,-0.028645,0.473928,-0.003190,-0.024338,0.008389,0.040585,-0.068471,-0.018512
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4265,98701,124568,292251,179,Malig neopl uterus NOS,2136-03-01 21:31:34,2136-03-02 18:35:05,F,2082-03-31,2136-03-11,...,0.015566,-0.028826,0.032944,-1.798152,0.010550,-0.006502,-0.004858,0.011612,0.035166,0.068875
4266,98701,124568,292251,1976,Sec mal neo peritoneum,2136-03-01 21:31:34,2136-03-02 18:35:05,F,2082-03-31,2136-03-11,...,0.015566,-0.028826,0.032944,-1.798152,0.010550,-0.006502,-0.004858,0.011612,0.035166,0.068875
4267,98701,124568,292251,1977,Second malig neo liver,2136-03-01 21:31:34,2136-03-02 18:35:05,F,2082-03-31,2136-03-11,...,0.015566,-0.028826,0.032944,-1.798152,0.010550,-0.006502,-0.004858,0.011612,0.035166,0.068875
4268,98701,124568,292251,1978,Sec mal neo GI NEC,2136-03-01 21:31:34,2136-03-02 18:35:05,F,2082-03-31,2136-03-11,...,0.015566,-0.028826,0.032944,-1.798152,0.010550,-0.006502,-0.004858,0.011612,0.035166,0.068875
4269,98805,122631,203155,1890,Malig neopl kidney,2200-09-12 19:25:51,2200-09-14 18:17:01,M,2158-03-02,NaT,...,NaN,NaN,-0.074101,-1.577445,-0.024257,-0.002827,-0.010009,0.101336,-0.143619,-0.092383

In [114]:

# 1. Calculate the percentage of non-null values for each column
completeness = onco_feature_df.count() / len(onco_feature_df)

# 2. Define a threshold for "most of its rows filled"
completeness_threshold = 0.9

# 3. Filter columns based on the completeness threshold
high_completeness_columns = completeness[completeness >= completeness_threshold].index.tolist()

print(f"Columns with at least {completeness_threshold*100}% of rows filled:")
print(high_completeness_columns)

# 4. Select these columns from the original DataFrame
onco_features_high_completeness = onco_feature_df[high_completeness_columns]

onco_features_high_completeness


# percentage or an absolute number of non-NaN values.
percentage_filled_threshold = 0.9 # Keep rows that are at least 75% filled

# Calculate the minimum number of non-NaN values required based on the percentage
num_columns = onco_features_high_completeness.shape[1]
min_non_nan_for_row = int(num_columns * percentage_filled_threshold)

print(f"Keeping rows with at least {min_non_nan_for_row} non-NaN values (i.e., {percentage_filled_threshold*100}% filled).")

# Drop rows using the calculated threshold
onco_cohort_ML = onco_features_high_completeness.dropna(
    axis=0,        # Operate on rows (default, but good to be explicit)
    thresh=min_non_nan_for_row
)

print("\nDataFrame after dropping rows that are less than {}% filled:".format(percentage_filled_threshold*100))
onco_cohort_ML

Columns with at least 90.0% of rows filled:
['subject_id', 'hadm_id', 'icustay_id', 'icd9_code', 'short_title', 'intime', 'outtime', 'gender', 'dob', 'admittime', 'ethnicity', 'marital_status', 'insurance', 'admission_type', 'age', 'mortality_30d', 'mean_heart_rate', 'mean_respiratory_rate', 'min_heart_rate', 'min_respiratory_rate', 'max_heart_rate', 'max_respiratory_rate', 'slope_heart_rate', 'slope_respiratory_rate', 'mean_anion_gap', 'mean_bicarbonate', 'mean_calcium,_total', 'mean_chloride', 'mean_creatinine_y', 'mean_glucose', 'mean_hematocrit', 'mean_hemoglobin_y', 'mean_mch', 'mean_mchc', 'mean_mcv', 'mean_magnesium_y', 'mean_phosphate', 'mean_platelet_count', 'mean_potassium', 'mean_rdw', 'mean_red_blood_cells', 'mean_sodium', 'mean_urea_nitrogen', 'mean_white_blood_cells', 'min_anion_gap', 'min_bicarbonate', 'min_calcium,_total', 'min_chloride', 'min_creatinine_y', 'min_glucose', 'min_hematocrit', 'min_hemoglobin_y', 'min_mch', 'min_mchc', 'min_mcv', 'min_magnesium_y', 'min_phosphate', 'min_platelet_count', 'min_potassium', 'min_rdw', 'min_red_blood_cells', 'min_sodium', 'min_urea_nitrogen', 'min_white_blood_cells', 'max_anion_gap', 'max_bicarbonate', 'max_calcium,_total', 'max_chloride', 'max_creatinine_y', 'max_glucose', 'max_hematocrit', 'max_hemoglobin_y', 'max_mch', 'max_mchc', 'max_mcv', 'max_magnesium_y', 'max_phosphate', 'max_platelet_count', 'max_potassium', 'max_rdw', 'max_red_blood_cells', 'max_sodium', 'max_urea_nitrogen', 'max_white_blood_cells', 'slope_anion_gap', 'slope_bicarbonate', 'slope_chloride', 'slope_creatinine_y', 'slope_glucose', 'slope_hematocrit', 'slope_hemoglobin_y', 'slope_mch', 'slope_mchc', 'slope_mcv', 'slope_platelet_count', 'slope_potassium', 'slope_rdw', 'slope_red_blood_cells', 'slope_sodium', 'slope_urea_nitrogen', 'slope_white_blood_cells']
Keeping rows with at least 90 non-NaN values (i.e., 90.0% filled).

DataFrame after dropping rows that are less than 90.0% filled:

,subject_id,hadm_id,icustay_id,icd9_code,short_title,intime,outtime,gender,dob,admittime,...,slope_mch,slope_mchc,slope_mcv,slope_platelet_count,slope_potassium,slope_rdw,slope_red_blood_cells,slope_sodium,slope_urea_nitrogen,slope_white_blood_cells
1,113,109976,224661,1915,Mal neo cereb ventricle,2140-12-12 22:48:08,2140-12-13 17:42:46,M,2105-02-09,2140-12-12 22:46:00,...,0.000013,-0.008797,0.014706,-0.776996,-0.010740,0.000000,-0.012172,-0.043983,0.024420,-0.075244
2,11,194540,229441,1913,Mal neo parietal lobe,2178-04-16 06:19:32,2178-04-17 20:21:05,F,2128-02-22,2178-04-16 06:18:00,...,0.046432,0.092863,-0.103181,-0.773861,-0.005159,0.005159,-0.007739,0.051591,0.257954,0.180567
3,505,116719,257903,1970,Secondary malig neo lung,2154-03-30 14:59:43,2154-03-31 16:35:08,M,2097-11-23,2154-03-30 14:59:00,...,0.027127,0.012673,0.048179,0.473928,-0.003190,-0.024338,0.008389,0.040585,-0.068471,-0.018512
4,505,116719,257903,1985,Secondary malig neo bone,2154-03-30 14:59:43,2154-03-31 16:35:08,M,2097-11-23,2154-03-30 14:59:00,...,0.027127,0.012673,0.048179,0.473928,-0.003190,-0.024338,0.008389,0.040585,-0.068471,-0.018512
5,389,134048,220654,2113,Benign neoplasm lg bowel,2104-04-18 01:36:24,2104-04-19 16:17:09,F,2031-06-17,2104-04-18 01:34:00,...,0.013605,0.007131,0.032247,-0.486618,-0.033513,-0.006281,0.016162,0.035028,-1.028498,-0.049935
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4265,98701,124568,292251,179,Malig neopl uterus NOS,2136-03-01 21:31:34,2136-03-02 18:35:05,F,2082-03-31,2136-03-01 21:30:00,...,0.041531,0.065605,-0.058843,-1.798152,0.010550,-0.006502,-0.004858,0.011612,0.035166,0.068875
4266,98701,124568,292251,1976,Sec mal neo peritoneum,2136-03-01 21:31:34,2136-03-02 18:35:05,F,2082-03-31,2136-03-01 21:30:00,...,0.041531,0.065605,-0.058843,-1.798152,0.010550,-0.006502,-0.004858,0.011612,0.035166,0.068875
4267,98701,124568,292251,1977,Second malig neo liver,2136-03-01 21:31:34,2136-03-02 18:35:05,F,2082-03-31,2136-03-01 21:30:00,...,0.041531,0.065605,-0.058843,-1.798152,0.010550,-0.006502,-0.004858,0.011612,0.035166,0.068875
4268,98701,124568,292251,1978,Sec mal neo GI NEC,2136-03-01 21:31:34,2136-03-02 18:35:05,F,2082-03-31,2136-03-01 21:30:00,...,0.041531,0.065605,-0.058843,-1.798152,0.010550,-0.006502,-0.004858,0.011612,0.035166,0.068875
4269,98805,122631,203155,1890,Malig neopl kidney,2200-09-12 19:25:51,2200-09-14 18:17:01,M,2158-03-02,2200-09-12 07:15:00,...,-0.013045,-0.009475,-0.023262,-1.577445,-0.024257,-0.002827,-0.010009,0.101336,-0.143619,-0.092383

In [106]:
onco_feature_df_high_completeness

,subject_id,hadm_id,icustay_id,icd9_code,short_title,intime,outtime,gender,dob,dod,...,slope_mch,slope_mchc,slope_mcv,slope_platelet_count,slope_potassium,slope_rdw,slope_red_blood_cells,slope_sodium,slope_urea_nitrogen,slope_white_blood_cells
1,113,109976,224661,1915,Mal neo cereb ventricle,2140-12-12 22:48:08,2140-12-13 17:42:46,M,2105-02-09,NaT,...,0.000013,-0.008797,0.014706,-0.776996,-0.010740,0.000000,-0.012172,-0.043983,0.024420,-0.075244
2,11,194540,229441,1913,Mal neo parietal lobe,2178-04-16 06:19:32,2178-04-17 20:21:05,F,2128-02-22,2178-11-14,...,0.046432,0.092863,-0.103181,-0.773861,-0.005159,0.005159,-0.007739,0.051591,0.257954,0.180567
3,505,116719,257903,1970,Secondary malig neo lung,2154-03-30 14:59:43,2154-03-31 16:35:08,M,2097-11-23,2154-08-29,...,0.027127,0.012673,0.048179,0.473928,-0.003190,-0.024338,0.008389,0.040585,-0.068471,-0.018512
4,505,116719,257903,1985,Secondary malig neo bone,2154-03-30 14:59:43,2154-03-31 16:35:08,M,2097-11-23,2154-08-29,...,0.027127,0.012673,0.048179,0.473928,-0.003190,-0.024338,0.008389,0.040585,-0.068471,-0.018512
5,389,134048,220654,2113,Benign neoplasm lg bowel,2104-04-18 01:36:24,2104-04-19 16:17:09,F,2031-06-17,2108-05-08,...,0.013605,0.007131,0.032247,-0.486618,-0.033513,-0.006281,0.016162,0.035028,-1.028498,-0.049935
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4265,98701,124568,292251,179,Malig neopl uterus NOS,2136-03-01 21:31:34,2136-03-02 18:35:05,F,2082-03-31,2136-03-11,...,0.041531,0.065605,-0.058843,-1.798152,0.010550,-0.006502,-0.004858,0.011612,0.035166,0.068875
4266,98701,124568,292251,1976,Sec mal neo peritoneum,2136-03-01 21:31:34,2136-03-02 18:35:05,F,2082-03-31,2136-03-11,...,0.041531,0.065605,-0.058843,-1.798152,0.010550,-0.006502,-0.004858,0.011612,0.035166,0.068875
4267,98701,124568,292251,1977,Second malig neo liver,2136-03-01 21:31:34,2136-03-02 18:35:05,F,2082-03-31,2136-03-11,...,0.041531,0.065605,-0.058843,-1.798152,0.010550,-0.006502,-0.004858,0.011612,0.035166,0.068875
4268,98701,124568,292251,1978,Sec mal neo GI NEC,2136-03-01 21:31:34,2136-03-02 18:35:05,F,2082-03-31,2136-03-11,...,0.041531,0.065605,-0.058843,-1.798152,0.010550,-0.006502,-0.004858,0.011612,0.035166,0.068875
4269,98805,122631,203155,1890,Malig neopl kidney,2200-09-12 19:25:51,2200-09-14 18:17:01,M,2158-03-02,NaT,...,-0.013045,-0.009475,-0.023262,-1.577445,-0.024257,-0.002827,-0.010009,0.101336,-0.143619,-0.092383